### PR TITLE
feature: Configure creating posts

### PR DESCRIPTION
**Pull request by JimTheCat**
- Configure creation of a new posts
- Enhance api interceptor
- Take basic user info to navbar
- Enhance RichEditor to return his value
- Correct roots
- Make strong nullcheck in MenuButton

Refs: CU-86973uu60

### CODE REVIEW

**Comment by JimTheCat** [comment]
Task linked: [CU-86973uu60 Configure "Create post"](https://app.clickup.com/t/86973uu60)

**Comment by JimTheCat** [comment]
image

**Comment by JimTheCat** [comment]
Also post itself correctly display injected html
image

**Review by KinTrae — APPROVED** [review]
Good job!

**Pull request merged**
